language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.1
branches:
  only:
    - master
script:
  - dotnet build -c Release
after_success:
  - dotnet publish -c Release
notifications:
  email:
    on_success: never
    on_failure: always

